### ISSUE TITLE
Can you make playable offline like the original?

### ISSUE THREAD

**Issue by 1Cadio** [MajesticWafer/dsp#1]
That’d be cool, thanks

**Comment by MajesticWafer** [comment]
Unfortunately this is an older fork of 44670’s DS Player, which does not include the ability to play offline. Their code is very hard to get ahold of, let alone working. I apologize!

**Comment by 1Cadio** [comment]
Oh, is there a way to archive the current website and I can put it in on github? It’s blocked for me

**Comment by MajesticWafer** [comment]
Yes, I believe you can host it on GitHub. You would first need to download
all the files.
